<?php

// v1.1 — 2026-06-12 | Add createOrderDiscountCoupon() — $10 single-use post-coverage discount,
//                     replicates the coupon previously generated by the sr-orders Zap.
// v1.0 — 2026-05-26 | WooCommerce REST API client — order list, detail, refund, resend email

namespace App\Services;

use Illuminate\Support\Facades\Http;
use Illuminate\Database\Eloquent\ModelNotFoundException;
use RuntimeException;

class WooCommerceService
{
    private string $baseUrl;
    private string $consumerKey;
    private string $consumerSecret;
    private string $portalSecret;

    public function __construct()
    {
        $this->baseUrl        = rtrim((string) config('services.woocommerce.store_url'), '/');
        $this->consumerKey    = (string) config('services.woocommerce.consumer_key');
        $this->consumerSecret = (string) config('services.woocommerce.consumer_secret');
        $this->portalSecret   = (string) config('services.woocommerce.portal_secret');
    }

    /**
     * List orders. Returns ['orders' => [...], 'total' => int, 'total_pages' => int].
     * Accepts any params the WC REST API supports: search, status, page, per_page, after, before.
     */
    public function getOrders(array $params = []): array
    {
        $response = Http::withBasicAuth($this->consumerKey, $this->consumerSecret)
            ->get($this->baseUrl . '/wp-json/wc/v3/orders', array_merge(['per_page' => 25, 'orderby' => 'date', 'order' => 'desc'], $params));

        if ($response->failed()) {
            throw new RuntimeException('WooCommerce API error (' . $response->status() . '): ' . ($response->json('message') ?? 'Unknown error'));
        }

        return [
            'orders'      => $response->json() ?? [],
            'total'       => (int) $response->header('X-WP-Total'),
            'total_pages' => (int) $response->header('X-WP-TotalPages'),
        ];
    }

    /**
     * Fetch a single order by WooCommerce order ID.
     * Throws ModelNotFoundException on 404, RuntimeException on other failures.
     */
    public function getOrder(int $id): array
    {
        $response = Http::withBasicAuth($this->consumerKey, $this->consumerSecret)
            ->get($this->baseUrl . "/wp-json/wc/v3/orders/{$id}");

        if ($response->status() === 404) {
            throw new ModelNotFoundException("Order {$id} not found.");
        }

        if ($response->failed()) {
            throw new RuntimeException('WooCommerce API error (' . $response->status() . '): ' . ($response->json('message') ?? 'Unknown error'));
        }

        return $response->json();
    }

    /**
     * Create a refund on an order. Delegates the actual gateway refund to WooCommerce
     * (api_refund: true), so Stripe/PayPal credentials never need to leave the WP site.
     */
    public function createRefund(int $orderId, float $amount, string $reason = ''): array
    {
        $response = Http::withBasicAuth($this->consumerKey, $this->consumerSecret)
            ->post($this->baseUrl . "/wp-json/wc/v3/orders/{$orderId}/refunds", [
                'amount'     => number_format($amount, 2, '.', ''),
                'reason'     => $reason,
                'api_refund' => true,
            ]);

        if ($response->failed()) {
            $message = $response->json('message') ?? 'Refund failed — the payment gateway may have rejected it.';
            throw new RuntimeException($message);
        }

        $refund = $response->json();

        // WooCommerce creates the refund record even if the gateway silently rejects it.
        // refunded_payment === false means the record exists in WC but no money moved.
        if (array_key_exists('refunded_payment', $refund) && $refund['refunded_payment'] === false) {
            throw new RuntimeException(
                'The refund was recorded in WooCommerce but the payment gateway did not process it — ' .
                'no money has been returned. Check the order notes in WooCommerce admin for details, ' .
                'and refund manually through the gateway if needed.'
            );
        }

        return $refund;
    }

    /**
     * Resend the order receipt (Completed Order) email via the custom sr/v1 REST endpoint
     * registered in woo_tweaks.php. Authenticated with WC_PORTAL_SECRET shared secret.
     *
     * The endpoint returns a 502 with a `message` describing the MailerSend error when
     * the send itself fails (e.g. bad template ID, unverified domain).
     */
    public function resendEmail(int $orderId, ?string $testEmail = null): void
    {
        $payload = $testEmail ? ['test_email' => $testEmail] : [];

        $response = Http::withHeaders(['X-SR-Portal-Secret' => $this->portalSecret])
            ->post($this->baseUrl . "/wp-json/sr/v1/orders/{$orderId}/resend-email", $payload);

        if ($response->failed()) {
            $message = $response->json('message') ?: ('Failed to resend email (' . $response->status() . ').');
            throw new RuntimeException($message);
        }
    }

    /**
     * Fetch published products — used to populate the coupon product selector.
     * Returns array of ['id' => int, 'name' => string, 'price' => string, 'type' => string].
     */
    public function getProducts(int $perPage = 100): array
    {
        $response = Http::withBasicAuth($this->consumerKey, $this->consumerSecret)
            ->get($this->baseUrl . '/wp-json/wc/v3/products', [
                'per_page' => $perPage,
                'status'   => 'publish',
                'orderby'  => 'title',
                'order'    => 'asc',
            ]);

        if ($response->failed()) {
            throw new RuntimeException('WooCommerce API error (' . $response->status() . '): ' . ($response->json('message') ?? 'Unknown error'));
        }

        return array_map(fn($p) => [
            'id'    => $p['id'],
            'name'  => $p['name'],
            'price' => $p['price'] ?? '',
            'type'  => $p['type'] ?? 'simple',
        ], $response->json() ?? []);
    }

    /**
     * Create a WooCommerce coupon for marketing campaigns.
     * Returns the created coupon array (includes 'id').
     *
     * $type:        'percent' or 'fixed_cart'
     * $productIds:  array of product IDs to restrict the coupon to (empty = sitewide)
     * $expiryDate:  'YYYY-MM-DD' or null for no expiry
     */
    /**
     * Fetch a single coupon by WooCommerce coupon ID.
     * Throws ModelNotFoundException on 404.
     */
    public function getCoupon(int $id): array
    {
        $response = Http::withBasicAuth($this->consumerKey, $this->consumerSecret)
            ->get($this->baseUrl . "/wp-json/wc/v3/coupons/{$id}");

        if ($response->status() === 404) {
            throw new ModelNotFoundException("Coupon {$id} not found.");
        }

        if ($response->failed()) {
            throw new RuntimeException('WooCommerce API error (' . $response->status() . '): ' . ($response->json('message') ?? 'Unknown error'));
        }

        return $response->json();
    }

    public function createCoupon(
        string  $code,
        string  $type,
        float   $amount,
        array   $productIds = [],
        ?string $expiryDate = null,
        string  $description = '',
        bool    $individualUse = true
    ): array {
        $payload = [
            'code'               => strtoupper($code),
            'discount_type'      => $type,
            'amount'             => number_format($amount, 2, '.', ''),
            'individual_use'     => $individualUse,
            'free_shipping'      => false,
            'description'        => $description,
        ];

        if (!empty($productIds)) {
            $payload['product_ids'] = array_map('intval', $productIds);
        }

        if ($expiryDate) {
            $payload['date_expires'] = $expiryDate;
        }

        $response = Http::withBasicAuth($this->consumerKey, $this->consumerSecret)
            ->post($this->baseUrl . '/wp-json/wc/v3/coupons', $payload);

        if ($response->failed()) {
            throw new RuntimeException('WooCommerce create coupon error (' . $response->status() . '): ' . ($response->json('message') ?? 'Unknown error'));
        }

        return $response->json();
    }

    /**
     * Create a $10 single-use, fixed-cart discount coupon (expires in 30 days).
     * Replicates the coupon previously generated by the sr-orders Zapier step —
     * sent to customers via {{woodiscountcode}} in the QC completion email.
     */
    public function createOrderDiscountCoupon(string $code): array
    {
        $payload = [
            'code'                 => $code,
            'amount'               => '10.00',
            'status'               => 'publish',
            'discount_type'        => 'fixed_cart',
            'description'          => '$10.00 off your next order',
            'date_expires'         => now()->addDays(30)->format('Y-m-d'),
            'individual_use'       => false,
            'free_shipping'        => false,
            'usage_limit'          => 1,
            'usage_limit_per_user' => 1,
        ];

        $response = Http::withBasicAuth($this->consumerKey, $this->consumerSecret)
            ->post($this->baseUrl . '/wp-json/wc/v3/coupons', $payload);

        if ($response->failed()) {
            throw new RuntimeException('WooCommerce create coupon error (' . $response->status() . '): ' . ($response->json('message') ?? 'Unknown error'));
        }

        return $response->json();
    }

    /**
     * Calculate the amount still refundable on an order (total minus already-refunded).
     * WC refund totals are stored as negative numbers, so we sum their absolute values.
     */
    public static function refundableAmount(array $order): float
    {
        $total    = (float) ($order['total'] ?? 0);
        $refunded = array_sum(array_map(fn($r) => abs((float) ($r['total'] ?? 0)), $order['refunds'] ?? []));

        return max(0.0, round($total - $refunded, 2));
    }
}
